from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Users(models.Model):
    name = models.CharField(max_length=200, null=True)
    email = models.CharField(max_length=200, null=True)
    last_name = models.CharField(max_length=200, null=True, default='')
    address = models.CharField(max_length=200, null=True, default='')
    date_created = models.DateTimeField(auto_now_add=True, null=True)
    
    def __str__(self):
        return self.name

class Locations(models.Model):
    name = models.CharField(max_length=200, null=True)
    fendering_position = models.CharField(max_length=1000, null=True, blank=True)
    STS_position = models.CharField(max_length=1000, null=True, blank=True)
    Fendering_position = models.CharField(max_length=1000, null=True, blank=True)
    STS_position = models.CharField(max_length=1000, null=True, blank=True)
    Cargos_permitted = models.CharField(max_length=1000, null=True, blank=True)
    Type_of_operation = models.CharField(max_length=1000, null=True, blank=True)
    Depth_of_water = models.CharField(max_length=1000, null=True, blank=True)
    Approval_to_conduct_STS_issued_by = models.CharField(max_length=1000, null=True, blank=True)
    Approval_needed_prior_to_each_STS_operation = models.CharField(max_length=1000, null=True, blank=True)
    Vessel_sizes_permitted = models.CharField(max_length=1000, null=True, blank=True)
    Night_time_berthing_permitted = models.CharField(max_length=1000, null=True, blank=True)
    Is_local_piloting_assistance_required = models.CharField(max_length=1000, null=True, blank=True)
    Are_tugs_required = models.CharField(max_length=1000, null=True, blank=True)
    Primary_Fenders = models.CharField(max_length=1000, null=True, blank=True)
    Secondary_Fenders = models.CharField(max_length=1000, null=True, blank=True)
    Fender_Moorings = models.CharField(max_length=1000, null=True, blank=True)
    Rubber_Hoses = models.CharField(max_length=1000, null=True, blank=True)
    Composite_Hoses = models.CharField(max_length=1000, null=True, blank=True)
    Agent_Company = models.CharField(max_length=1000, null=True, blank=True)
    Agent_Contact = models.CharField(max_length=1000, null=True, blank=True)
    Fees_to_be_incurred_for_STS_Operations = models.DecimalField(max_digits=20, decimal_places=2, null=True, blank=True)
    Base_Location = models.CharField(max_length=1000, null=True, blank=True)
    Storage_Space = models.CharField(max_length=1000, null=True, blank=True)
    Security_Arrangements = models.CharField(max_length=1000, null=True, blank=True)
    Closest_Airport = models.CharField(max_length=1000, null=True, blank=True)
    Local_taxi_firms = models.CharField(max_length=1000, null=True, blank=True)
    Accommodation = models.CharField(max_length=1000, null=True, blank=True)
    Base_facilities = models.CharField(max_length=1000, null=True, blank=True)
    Notice_Period = models.CharField(max_length=1000, null=True, blank=True)
    Documentation_Requirements = models.CharField(max_length=1000, null=True, blank=True)
    Vessel_Name = models.CharField(max_length=1000, null=True, blank=True)
    Support_Craft_Owner = models.CharField(max_length=1000, null=True, blank=True)
    Telephone = models.CharField(max_length=1000, null=True, blank=True)
    Tug_Provider_Company = models.CharField(max_length=1000, null=True, blank=True)
    Tug_Provider_Contact = models.CharField(max_length=1000, null=True, blank=True)
    Tug_Provider_Vessel_Name = models.CharField(max_length=1000, null=True, blank=True)
    Location_under_the_control_of_authorities = models.CharField(max_length=1000, null=True, blank=True)
    Current_port_security_level = models.CharField(max_length=1000, null=True, blank=True)
    What_is_considered_port_limits = models.CharField(max_length=1000, null=True, blank=True)
    What_is_considered_international_waters = models.CharField(max_length=1000, null=True, blank=True)
    Distance_from_support_base = models.CharField(max_length=1000, null=True, blank=True)
    Transit_time_from_shore_to_STS_location = models.CharField(max_length=1000, null=True, blank=True)
    Size_of_transfer_area = models.CharField(max_length=1000, null=True, blank=True)
    Does_the_area_have_a_large_enough_run_in_area = models.CharField(max_length=1000, null=True, blank=True)
    Is_the_transfer_area_sheltered = models.CharField(max_length=1000, null=True, blank=True)
    Regulations_to_be_complied_during_the_operation = models.CharField(max_length=1000, null=True, blank=True)
    Nature_of_seabed = models.CharField(max_length=1000, null=True, blank=True)
    Average_depth_of_water = models.CharField(max_length=1000, null=True, blank=True)
    STS_location_suitable_for_anchoring = models.CharField(max_length=1000, null=True, blank=True)
    Any_other_service_provider_in_the_same_vicinity = models.CharField(max_length=1000, null=True, blank=True)
    Local_marine_activity = models.CharField(max_length=1000, null=True, blank=True)
    Any_physical_limitations_on_vessel_size = models.CharField(max_length=1000, null=True, blank=True)
    Distance_from_land = models.CharField(max_length=1000, null=True, blank=True)
    Any_other_navigational_hazards_in_the_area = models.CharField(max_length=1000, null=True, blank=True)
    Prevailing_winds = models.CharField(max_length=1000, null=True, blank=True)
    Predominant_current = models.CharField(max_length=1000, null=True, blank=True)
    Average_wave_height = models.CharField(max_length=1000, null=True, blank=True)
    Average_swell_height_and_period = models.CharField(max_length=1000, null=True, blank=True)
    What_is_the_tidal_range_if_applicable = models.CharField(max_length=1000, null=True, blank=True)
    Location_subject_to_restrictive_Met_conditions = models.CharField(max_length=1000, null=True, blank=True)
    STS_Location_covered_by_forecasting_service = models.CharField(max_length=1000, null=True, blank=True)
    Location_adjacent_to_any_public_sensitive_areas = models.CharField(max_length=1000, null=True, blank=True)
    Environmental_bodies_to_be_advised_of_operations = models.CharField(max_length=1000, null=True, blank=True)
    Local_oil_pollution_prevention_requirements = models.CharField(max_length=1000, null=True, blank=True)
    STS_area_covered_by_oil_spill_organisation = models.CharField(max_length=1000, null=True, blank=True)
    Contract_directly_with_an_Oil_pollution_contractor = models.CharField(max_length=1000, null=True, blank=True)
    Oil_Spill_Responders = models.CharField(max_length=1000, null=True, blank=True)
    Local_Emergency_Medical_Assistance = models.CharField(max_length=1000, null=True, blank=True)
    Police = models.CharField(max_length=1000, null=True, blank=True)
    Coast_Guard = models.CharField(max_length=1000, null=True, blank=True)
    Fire_fighting = models.CharField(max_length=1000, null=True, blank=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return self.name
