# Generated by Django 3.0.7 on 2020-06-22 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_locations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='STS_position',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='locations',
            name='fendering_position',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
